;BCD TO HEX IN 8051

START:
MOV R1, #28H		;INITIAL BCD VALUE

MOV A, R1
ANL A, #0FH		;TAKE THE LOWER NIBBLE
MOV R2, A		;PUT IT IN R2
MOV A, R1
ANL A, #0F0H		;TAKE THE HIGHER NIBBLE
SWAP A			;SWAP LOWER AND HIGHER NIBBLE

			;HIGHER NIBBLE * 10 + LOWER NIBBLE

MOV B, #0AH		; MSB * 10
MUL AB			; TO PERFORM HIGHER NIBBLE * 10

ADD A, R2		; + LSB
MOV R2, A		;RESULT TO R2

HALT:
SJMP HALT